kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: group2-rolebinding
  namespace: local-user-authenticator
subjects:
- kind: Group
  name: group2
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: bmullan2-namespace-role
  apiGroup: rbac.authorization.k8s.io
