kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: local-user-authenticator
  name: bmullan2-namespace-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]

